configure.ac:  Workaround to fix Snap build
Building this library in a Printer Application Snap (with core 20)
causes the error

configure.ac:105: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
error: autoconf failed

when running autogen.sh. Following the hint in the error message added
the line

m4_pattern_allow([AC_DEFINE])

to configure.ac which makes the error go away.